#!/bin/bash

sudo yum check-update
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl status docker

sudo docker pull postgres:13.4-buster
sudo docker pull jupyterhub/jupyterhub:1.0.0

sudo docker run -d -p5432:5432 --name postgres -e POSTGRES_PASSWORD=$1 postgres:13.4-buster postgres
sudo docker run -d -p8000:8000 --name jupyterhub jupyterhub/jupyterhub:1.0.0 jupyterhub

sudo yum install python3

pip3 install -U pip
pip install psycopg2-binary
pip install pandas